{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "http://localhost:3000/api"
    }
  ],
  "paths": {
    "/auth/user/update": {
      "parameters": [],
      "post": {
        "summary": "Update User",
        "operationId": "auth_updateUser",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Update user data.",
        "tags": ["auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/auth_user"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "uuid": "string",
                    "from": "string",
                    "password": "string",
                    "role": "string",
                    "data": {
                      "displayName": "string",
                      "photoURL": "string",
                      "email": "string",
                      "settings": {
                        "layout": {},
                        "theme": {}
                      },
                      "shortcuts": ["string"]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/sign-in": {
      "get": {
        "summary": "Sign In",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/auth_user"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "uuid": "string",
                      "from": "string",
                      "password": "string",
                      "role": "string",
                      "data": {
                        "displayName": "string",
                        "photoURL": "string",
                        "email": "string",
                        "settings": {
                          "layout": {},
                          "theme": {}
                        },
                        "shortcuts": ["string"]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "auth_signIn",
        "description": "Retrieve user.",
        "tags": ["auth"]
      },
      "parameters": []
    },
    "/auth/sign-up": {
      "get": {
        "summary": "Sign Up",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/auth_user"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "uuid": "string",
                      "from": "string",
                      "password": "string",
                      "role": "string",
                      "data": {
                        "displayName": "string",
                        "photoURL": "string",
                        "email": "string",
                        "settings": {
                          "layout": {},
                          "theme": {}
                        },
                        "shortcuts": ["string"]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "auth_signUp",
        "description": "Retrieve user.",
        "tags": ["auth"]
      },
      "parameters": []
    },
    "/auth/access-token": {
      "get": {
        "summary": "Sign in with access token",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/auth_user"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "uuid": "string",
                      "from": "string",
                      "password": "string",
                      "role": "string",
                      "data": {
                        "displayName": "string",
                        "photoURL": "string",
                        "email": "string",
                        "settings": {
                          "layout": {},
                          "theme": {}
                        },
                        "shortcuts": ["string"]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "auth_signInWithAccessToken",
        "description": "Retrieve user with access token.",
        "tags": ["auth"]
      },
      "parameters": []
    },
    "/dashboards/project/widgets": {
      "get": {
        "summary": "Get Project Dashboard Widgets",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "example-1": {
                    "$ref": "#/components/examples/project_dashboard_widgets"
                  }
                }
              }
            }
          }
        },
        "operationId": "projectDashboard_getWidgetsidgets",
        "description": "Retrieve Project dashboard widgets.",
        "tags": ["project-dashboard"]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "auth_user": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "from": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "displayName": {
                "type": "string"
              },
              "photoURL": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "settings": {
                "type": "object",
                "properties": {
                  "layout": {
                    "type": "object",
                    "properties": {}
                  },
                  "theme": {
                    "type": "object",
                    "properties": {}
                  }
                }
              },
              "shortcuts": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "x-examples": {
          "example-1": {
            "uuid": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
            "from": "custom-db",
            "password": "admin",
            "role": "admin",
            "data": {
              "displayName": "Abbott Keitch",
              "photoURL": "assets/images/avatars/brian-hughes.jpg",
              "email": "admin@fusetheme.com",
              "settings": {
                "layout": {},
                "theme": {}
              },
              "shortcuts": ["apps.calendar", "apps.mailbox", "apps.contacts"]
            }
          }
        }
      }
    },
    "securitySchemes": {},
    "examples": {
      "project_dashboard_widgets": {
        "value": {
          "summary": {
            "ranges": {
              "DY": "Yesterday",
              "DT": "Today",
              "DTM": "Tomorrow"
            },
            "currentRange": "DT",
            "data": {
              "name": "Due Tasks",
              "count": {
                "DY": 21,
                "DT": 25,
                "DTM": 19
              },
              "extra": {
                "name": "Completed",
                "count": {
                  "DY": 6,
                  "DT": 7,
                  "DTM": "-"
                }
              }
            },
            "detail": "You can show some detailed information about this widget in here."
          },
          "githubIssues": {
            "overview": {
              "this-week": {
                "new-issues": 214,
                "closed-issues": 75,
                "fixed": 3,
                "wont-fix": 4,
                "re-opened": 8,
                "needs-triage": 6
              },
              "last-week": {
                "new-issues": 197,
                "closed-issues": 72,
                "fixed": 6,
                "wont-fix": 11,
                "re-opened": 6,
                "needs-triage": 5
              }
            },
            "ranges": {
              "this-week": "This Week",
              "last-week": "Last Week"
            },
            "labels": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
            "series": {
              "this-week": [
                {
                  "name": "New issues",
                  "type": "line",
                  "data": [42, 28, 43, 34, 20, 25, 22]
                },
                {
                  "name": "Closed issues",
                  "type": "column",
                  "data": [11, 10, 8, 11, 8, 10, 17]
                }
              ],
              "last-week": [
                {
                  "name": "New issues",
                  "type": "line",
                  "data": [37, 32, 39, 27, 18, 24, 20]
                },
                {
                  "name": "Closed issues",
                  "type": "column",
                  "data": [9, 8, 10, 12, 7, 11, 15]
                }
              ]
            }
          },
          "budgetDistribution": {
            "categories": [
              "Concept",
              "Design",
              "Development",
              "Extras",
              "Marketing"
            ],
            "series": [
              {
                "name": "Budget",
                "data": [12, 20, 28, 15, 25]
              }
            ]
          },
          "budgetDetails": {
            "columns": [
              "Type",
              "Total Budget",
              "Expenses (USD)",
              "Expenses (%)",
              "Remaining (USD)",
              "Remaining (%)"
            ],
            "rows": [
              {
                "type": "Concept",
                "total": 14880,
                "expensesAmount": 14000,
                "expensesPercentage": 94.08,
                "remainingAmount": 880,
                "remainingPercentage": 5.92
              },
              {
                "type": "Design",
                "total": 21080,
                "expensesAmount": 17240.34,
                "expensesPercentage": 81.78,
                "remainingAmount": 3839.66,
                "remainingPercentage": 18.22
              },
              {
                "type": "Development",
                "total": 34720,
                "expensesAmount": 3518,
                "expensesPercentage": 10.13,
                "remainingAmount": 31202,
                "remainingPercentage": 89.87
              },
              {
                "type": "Extras",
                "total": 18600,
                "expensesAmount": 0,
                "expensesPercentage": 0,
                "remainingAmount": 18600,
                "remainingPercentage": 100
              },
              {
                "type": "Marketing",
                "total": 34720,
                "expensesAmount": 19859.84,
                "expensesPercentage": 57.2,
                "remainingAmount": 14860.16,
                "remainingPercentage": 42.8
              }
            ]
          },
          "teamMembers": [
            {
              "id": "2bfa2be5-7688-48d5-b5ac-dc0d9ac97f14",
              "avatar": "assets/images/avatars/female-10.jpg",
              "name": "Nadia Mcknight",
              "email": "nadiamcknight@mail.com",
              "phone": "+1-943-511-2203",
              "title": "Project Director"
            }
          ]
        }
      },
      "auth_users": {
        "value": [
          {
            "uuid": "XgbuVEXBU5gtSKdbQRP1Zbbby1i1",
            "from": "custom-db",
            "password": "admin",
            "role": "admin",
            "data": {
              "displayName": "Loyals app",
              "photoURL": "assets/images/avatars/brian-hughes.jpg",
              "email": "admin@loyals.com",
              "settings": {
                "layout": {},
                "theme": {}
              },
              "shortcuts": ["apps.calendar", "apps.mailbox", "apps.contacts"]
            }
          }
        ]
      }
    },
    "responses": {}
  }
}
